CREATE SCHEMA `wallet` ;


CREATE TABLE `wallet`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `mobile` VARCHAR(11) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `balance` FLOAT NOT NULL DEFAULT 0.0,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC) VISIBLE);


CREATE TABLE `wallet`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(11) NULL,
  `destination` VARCHAR(11) NOT NULL,
  `amount` FLOAT NOT NULL DEFAULT 0.0,
  `type` TINYINT(1) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
